global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "upupup_checks"
    scheme: http
    static_configs:
      - targets: ["server:8080"]
        labels:
          check_id: ms-portal
      - targets: ["server:8080"]
        labels:
          check_id: ms-portal-healthcheck
      - targets: ["server:8080"]
        labels:
          check_id: ms-sentry
      - targets: ["server:8080"]
        labels:
          check_id: ms-account
      - targets: ["server:8080"]
        labels:
          check_id: mc-connpass
      - targets: ["server:8080"]
        labels:
          check_id: mc-folder
      - targets: ["server:8080"]
        labels:
          check_id: help.gov.ua
    relabel_configs:
      - source_labels: [check_id]
        regex: (.*)
        target_label: __metrics_path__
        replacement: /api/data/$1

